// Auto-generated by scripts/update-reference-manifest.mjs
export const REFERENCE_FILES = [
  "00-index.md",
  "01-repo-setup.md",
  "02-tsconfig.md",
  "03-best-practices.md",
  "04-data-types.md",
  "05-error-handling.md",
  "06-config.md"
] as const;
